### ISSUE TITLE
Stage 5 TODO

### ISSUE THREAD

**Issue by tahoe01** [dayuebai/GroupBuy#4]
- [x] Basic function: allow users to join teams
- [x] Insert enough data for demo (more users, more products, more teams, …., ideally 20 users, 20 products, 10 teams)
- [x] @yuansun97  ranking board (involve join query)
- [x] AF1: fuzzy search 
- [x] AF2: mongdb setup, follow feature, display followers and followees for each user (try showing follow relationship graph on the frontend using some frontend library ). **To help user find followers, we can have another page that recommends some popular users (or just show all users in DB).
- [ ] Final merge and Check
- [ ] Deploy to Azure (remote server)
- [ ] Demo to TA (date: 11/30 - 12/2)
- [ ] Final project report (ddl: 10pm 12/5)
- [ ] Demo video on YouTube (ddl 11:50pm 12/5)
